spring:
  application:
    name: market-intelligence-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/market-migration
    baseline-on-migrate: true
    validate-on-migrate: false

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html